---

- name: install necessities(git, python3, venv, and pip)
  hosts: all
  become: yes
  tasks:
    - name: install git
      ansible.builtin.package:
        name: git
        state: latest
    - name: install python3
      ansible.builtin.package:
        name: python3
        state: latest
    - name: install python3-venv
      ansible.builtin.package:
        name: python3-venv
        state: latest
    - name: install python3-pip
      ansible.builtin.package:
        name: python3-pip
        state: latest






- name: get code from git repo, set up venv, install requirements


  hosts: all
  tasks:
    - name: clone the git repo first
      ansible.builtin.git:
        repo: https://github.com/2105-may24-devops/john-project0.git
        dest: john-project0
        single_branch: yes
        version: main

    - name: next, set up the venv with everything needed to run the program
      ansible.builtin.shell: python3 -m venv venv
      args: 
        chdir: john-project0
        
    - name: installing requirements
      requirements: /john-project0/requirements.txt
      virtualenv: /john-project0/venv/




    