---

- name: Run test bash script
  hosts: all
  tasks:
    - name: run the cryptos_tests shell script file
      script: cryptos_tests.sh
      register: testresults
      args: 
        chdir: /home/john/john-project0/
    - debug: var=testresults.stdout_lines
